
/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/
#include "can_messages_tx.h"
#include <stdbool.h>

#include "u_tx_debug.h"
#include "u_queues.h"
#include "c_utils.h"
#include "fdcan.h"
#include "bitstream.h"


static void handle_bitstream_overflow(bitstream_t *bitstream_res,
					    uint32_t can_id);

uint8_t send_front_msb_env
(float temp,float humidity)
{
    can_msg_t msg;
    msg.id = 0x602;
    msg.id_is_extended = false;
    
            uint32_t data = 0;
            msg.len = 4;
                        uint32_t temp_i = (uint32_t)(temp*10);
                        if(temp_i > 65535ULL) {temp_i = 65535;
                        }
                        data |= ((temp_i) & 0xFFFFULL) << 16;
            
                        uint32_t humidity_i = (uint32_t)(humidity*10);
                        if(humidity_i > 65535ULL) {humidity_i = 65535;
                        }
                        data |= ((humidity_i) & 0xFFFFULL) << 0;
            
            uint32_t data_bigendian = __builtin_bswap32(data);
            memcpy(msg.data, &data_bigendian, 4);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_msb_accel
(float x_force,float y_force,float z_force)
{
    can_msg_t msg;
    msg.id = 0x603;
    msg.id_is_extended = false;
    
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_force_i = (int32_t)(x_force);
                        if(x_force_i > 32767) {x_force_i = 32767;
                        } else if(x_force_i < -32768) {x_force_i = -32768;
                        }
                        data |= ((uint32_t)(x_force_i) & 0xFFFFULL) << 48;
            
                        int32_t y_force_i = (int32_t)(y_force);
                        if(y_force_i > 32767) {y_force_i = 32767;
                        } else if(y_force_i < -32768) {y_force_i = -32768;
                        }
                        data |= ((uint32_t)(y_force_i) & 0xFFFFULL) << 32;
            
                        int32_t z_force_i = (int32_t)(z_force);
                        if(z_force_i > 32767) {z_force_i = 32767;
                        } else if(z_force_i < -32768) {z_force_i = -32768;
                        }
                        data |= ((uint32_t)(z_force_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_msb_gyro
(float x_deg,float y_deg,float z_deg)
{
    can_msg_t msg;
    msg.id = 0x604;
    msg.id_is_extended = false;
    
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_deg_i = (int32_t)(x_deg);
                        if(x_deg_i > 32767) {x_deg_i = 32767;
                        } else if(x_deg_i < -32768) {x_deg_i = -32768;
                        }
                        data |= ((uint32_t)(x_deg_i) & 0xFFFFULL) << 48;
            
                        int32_t y_deg_i = (int32_t)(y_deg);
                        if(y_deg_i > 32767) {y_deg_i = 32767;
                        } else if(y_deg_i < -32768) {y_deg_i = -32768;
                        }
                        data |= ((uint32_t)(y_deg_i) & 0xFFFFULL) << 32;
            
                        int32_t z_deg_i = (int32_t)(z_deg);
                        if(z_deg_i > 32767) {z_deg_i = 32767;
                        } else if(z_deg_i < -32768) {z_deg_i = -32768;
                        }
                        data |= ((uint32_t)(z_deg_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_msb_strain
(uint32_t strain1,uint32_t strain2)
{
    can_msg_t msg;
    msg.id = 0x605;
    msg.id_is_extended = false;
    
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t strain1_i = (uint32_t)(strain1);
                        if(strain1_i > 4294967295ULL) {strain1_i = 4294967295;
                        }
                        data |= ((strain1_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t strain2_i = (uint32_t)(strain2);
                        if(strain2_i > 4294967295ULL) {strain2_i = 4294967295;
                        }
                        data |= ((strain2_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_shockpot
(float shock1,uint16_t shock1_raw)
{
    can_msg_t msg;
    msg.id = 0x606;
    msg.id_is_extended = false;
    struct __attribute__((__packed__)) {
        uint32_t shock1;
        uint16_t shock1_raw;
        
    } bitstream_data;
    
    bitstream_data.shock1 = (uint32_t)(shock1);
        
    bitstream_data.shock1_raw = (uint16_t)(shock1_raw);
        
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_ride_height
(float rh)
{
    can_msg_t msg;
    msg.id = 0x607;
    msg.id_is_extended = false;
    
            uint16_t data = 0;
            msg.len = 2;
                        int32_t rh_i = (int32_t)(rh);
                        if(rh_i > 32767) {rh_i = 32767;
                        } else if(rh_i < -32768) {rh_i = -32768;
                        }
                        data |= ((uint32_t)(rh_i) & 0xFFFFULL) << 0;
            
            uint16_t data_bigendian = __builtin_bswap16(data);
            memcpy(msg.data, &data_bigendian, 2);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_wheel_temp
(float wheel_temp)
{
    can_msg_t msg;
    msg.id = 0x608;
    msg.id_is_extended = false;
    
            uint16_t data = 0;
            msg.len = 2;
                        uint32_t wheel_temp_i = (uint32_t)(wheel_temp);
                        if(wheel_temp_i > 65535ULL) {wheel_temp_i = 65535;
                        }
                        data |= ((wheel_temp_i) & 0xFFFFULL) << 0;
            
            uint16_t data_bigendian = __builtin_bswap16(data);
            memcpy(msg.data, &data_bigendian, 2);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_msb_orientation
(float x_fdeg,float y_fdeg,float z_fdeg)
{
    can_msg_t msg;
    msg.id = 0x609;
    msg.id_is_extended = false;
    
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_fdeg_i = (int32_t)(x_fdeg);
                        if(x_fdeg_i > 32767) {x_fdeg_i = 32767;
                        } else if(x_fdeg_i < -32768) {x_fdeg_i = -32768;
                        }
                        data |= ((uint32_t)(x_fdeg_i) & 0xFFFFULL) << 48;
            
                        int32_t y_fdeg_i = (int32_t)(y_fdeg);
                        if(y_fdeg_i > 32767) {y_fdeg_i = 32767;
                        } else if(y_fdeg_i < -32768) {y_fdeg_i = -32768;
                        }
                        data |= ((uint32_t)(y_fdeg_i) & 0xFFFFULL) << 32;
            
                        int32_t z_fdeg_i = (int32_t)(z_fdeg);
                        if(z_fdeg_i > 32767) {z_fdeg_i = 32767;
                        } else if(z_fdeg_i < -32768) {z_fdeg_i = -32768;
                        }
                        data |= ((uint32_t)(z_fdeg_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_env
(float temp,float humidity)
{
    can_msg_t msg;
    msg.id = 0x622;
    msg.id_is_extended = false;
    
            uint32_t data = 0;
            msg.len = 4;
                        uint32_t temp_i = (uint32_t)(temp*10);
                        if(temp_i > 65535ULL) {temp_i = 65535;
                        }
                        data |= ((temp_i) & 0xFFFFULL) << 16;
            
                        uint32_t humidity_i = (uint32_t)(humidity*10);
                        if(humidity_i > 65535ULL) {humidity_i = 65535;
                        }
                        data |= ((humidity_i) & 0xFFFFULL) << 0;
            
            uint32_t data_bigendian = __builtin_bswap32(data);
            memcpy(msg.data, &data_bigendian, 4);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_accel
(float x_force,float y_force,float z_force)
{
    can_msg_t msg;
    msg.id = 0x623;
    msg.id_is_extended = false;
    
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_force_i = (int32_t)(x_force);
                        if(x_force_i > 32767) {x_force_i = 32767;
                        } else if(x_force_i < -32768) {x_force_i = -32768;
                        }
                        data |= ((uint32_t)(x_force_i) & 0xFFFFULL) << 48;
            
                        int32_t y_force_i = (int32_t)(y_force);
                        if(y_force_i > 32767) {y_force_i = 32767;
                        } else if(y_force_i < -32768) {y_force_i = -32768;
                        }
                        data |= ((uint32_t)(y_force_i) & 0xFFFFULL) << 32;
            
                        int32_t z_force_i = (int32_t)(z_force);
                        if(z_force_i > 32767) {z_force_i = 32767;
                        } else if(z_force_i < -32768) {z_force_i = -32768;
                        }
                        data |= ((uint32_t)(z_force_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_gyro
(float x_deg,float y_deg,float z_deg)
{
    can_msg_t msg;
    msg.id = 0x624;
    msg.id_is_extended = false;
    
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_deg_i = (int32_t)(x_deg);
                        if(x_deg_i > 32767) {x_deg_i = 32767;
                        } else if(x_deg_i < -32768) {x_deg_i = -32768;
                        }
                        data |= ((uint32_t)(x_deg_i) & 0xFFFFULL) << 48;
            
                        int32_t y_deg_i = (int32_t)(y_deg);
                        if(y_deg_i > 32767) {y_deg_i = 32767;
                        } else if(y_deg_i < -32768) {y_deg_i = -32768;
                        }
                        data |= ((uint32_t)(y_deg_i) & 0xFFFFULL) << 32;
            
                        int32_t z_deg_i = (int32_t)(z_deg);
                        if(z_deg_i > 32767) {z_deg_i = 32767;
                        } else if(z_deg_i < -32768) {z_deg_i = -32768;
                        }
                        data |= ((uint32_t)(z_deg_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_strain
(uint32_t strain1,uint32_t strain2)
{
    can_msg_t msg;
    msg.id = 0x625;
    msg.id_is_extended = false;
    
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t strain1_i = (uint32_t)(strain1);
                        if(strain1_i > 4294967295ULL) {strain1_i = 4294967295;
                        }
                        data |= ((strain1_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t strain2_i = (uint32_t)(strain2);
                        if(strain2_i > 4294967295ULL) {strain2_i = 4294967295;
                        }
                        data |= ((strain2_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_shockpot
(float shock1,uint16_t shock1_raw)
{
    can_msg_t msg;
    msg.id = 0x626;
    msg.id_is_extended = false;
    struct __attribute__((__packed__)) {
        uint32_t shock1;
        uint16_t shock1_raw;
        
    } bitstream_data;
    
    bitstream_data.shock1 = (uint32_t)(shock1);
        
    bitstream_data.shock1_raw = (uint16_t)(shock1_raw);
        
    memcpy(msg.data, &bitstream_data, sizeof(bitstream_data));

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_ride_height
(float rh)
{
    can_msg_t msg;
    msg.id = 0x627;
    msg.id_is_extended = false;
    
            uint16_t data = 0;
            msg.len = 2;
                        int32_t rh_i = (int32_t)(rh);
                        if(rh_i > 32767) {rh_i = 32767;
                        } else if(rh_i < -32768) {rh_i = -32768;
                        }
                        data |= ((uint32_t)(rh_i) & 0xFFFFULL) << 0;
            
            uint16_t data_bigendian = __builtin_bswap16(data);
            memcpy(msg.data, &data_bigendian, 2);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_wheel_temp
(float wheel_temp)
{
    can_msg_t msg;
    msg.id = 0x628;
    msg.id_is_extended = false;
    
            uint16_t data = 0;
            msg.len = 2;
                        uint32_t wheel_temp_i = (uint32_t)(wheel_temp);
                        if(wheel_temp_i > 65535ULL) {wheel_temp_i = 65535;
                        }
                        data |= ((wheel_temp_i) & 0xFFFFULL) << 0;
            
            uint16_t data_bigendian = __builtin_bswap16(data);
            memcpy(msg.data, &data_bigendian, 2);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_orientation
(float x_fdeg,float y_fdeg,float z_fdeg)
{
    can_msg_t msg;
    msg.id = 0x629;
    msg.id_is_extended = false;
    
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_fdeg_i = (int32_t)(x_fdeg);
                        if(x_fdeg_i > 32767) {x_fdeg_i = 32767;
                        } else if(x_fdeg_i < -32768) {x_fdeg_i = -32768;
                        }
                        data |= ((uint32_t)(x_fdeg_i) & 0xFFFFULL) << 48;
            
                        int32_t y_fdeg_i = (int32_t)(y_fdeg);
                        if(y_fdeg_i > 32767) {y_fdeg_i = 32767;
                        } else if(y_fdeg_i < -32768) {y_fdeg_i = -32768;
                        }
                        data |= ((uint32_t)(y_fdeg_i) & 0xFFFFULL) << 32;
            
                        int32_t z_fdeg_i = (int32_t)(z_fdeg);
                        if(z_fdeg_i > 32767) {z_fdeg_i = 32767;
                        } else if(z_fdeg_i < -32768) {z_fdeg_i = -32768;
                        }
                        data |= ((uint32_t)(z_fdeg_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_wheel_speed
(uint32_t wheel_speed_mph,uint32_t wheel_speed_rpm)
{
    can_msg_t msg;
    msg.id = 0x630;
    msg.id_is_extended = false;
    
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t wheel_speed_mph_i = (uint32_t)(wheel_speed_mph*10);
                        if(wheel_speed_mph_i > 4294967295ULL) {wheel_speed_mph_i = 4294967295;
                        }
                        data |= ((wheel_speed_mph_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t wheel_speed_rpm_i = (uint32_t)(wheel_speed_rpm*10);
                        if(wheel_speed_rpm_i > 4294967295ULL) {wheel_speed_rpm_i = 4294967295;
                        }
                        data |= ((wheel_speed_rpm_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}



/// @brief A helper which sends appropriate error to stdout and CAN if a bistream overflows
/// @param bitstream_res The bitstream to check for overflow
/// @param can_id The CAN ID this bistream data is intended for
/// @return 0 if success
static void handle_bitstream_overflow(bitstream_t *bitstream_res,
					    uint32_t can_id)
{
	if (!bitstream_res->overflow) {
		return;
	}

    
}