#ifndef _CAN_MSGS_TX_H
#define _CAN_MSGS_TX_H

/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/
#include <stdbool.h>
#include <stdint.h>

/**
* Contents of this message:
* MSB/F/Temp - Temperature of board
* MSB/F/Humidity - Humidity of board
*/
uint8_t send_front_msb_env
(float temp,float humidity);

/**
* Contents of this message:
* MSB/F/Accel - IMU readings from the board
*/
uint8_t send_front_msb_accel
(float x_force,float y_force,float z_force);

/**
* Contents of this message:
* MSB/F/Gyro - Gyro readings from the board
*/
uint8_t send_front_msb_gyro
(float x_deg,float y_deg,float z_deg);

/**
* Contents of this message:
* MSB/F/Strain - Strain readings
*/
uint8_t send_front_msb_strain
(uint32_t strain1,uint32_t strain2);

/**
* Contents of this message:
* MSB/F/Shock - Shuck deflection
* MSB/F/ShockRaw - Raw shock value
*/
uint8_t send_front_shockpot
(float shock1,uint16_t shock1_raw);

/**
* Contents of this message:
* MSB/F/RideHeight - Ride height to sensor
*/
uint8_t send_front_ride_height
(float rh);

/**
* Contents of this message:
* MSB/F/WheelTemp - As-measured wheel temperature
*/
uint8_t send_front_wheel_temp
(float wheel_temp);

/**
* Contents of this message:
* MSB/F/Orientation - MSB orientation as a result of sensor fusion
*/
uint8_t send_front_msb_orientation
(float x_fdeg,float y_fdeg,float z_fdeg);

/**
* Contents of this message:
* MSB/B/Temp - Temperature of board
* MSB/B/Humidity - Humidity of board
*/
uint8_t send_back_msb_env
(float temp,float humidity);

/**
* Contents of this message:
* MSB/B/Accel - IMU readings from the board
*/
uint8_t send_back_msb_accel
(float x_force,float y_force,float z_force);

/**
* Contents of this message:
* MSB/B/Gyro - Gyro readings from the board
*/
uint8_t send_back_msb_gyro
(float x_deg,float y_deg,float z_deg);

/**
* Contents of this message:
* MSB/B/Strain - Strain readings
*/
uint8_t send_back_msb_strain
(uint32_t strain1,uint32_t strain2);

/**
* Contents of this message:
* MSB/B/Shock - Shuck deflection
* MSB/B/ShockRaw - Raw shock value
*/
uint8_t send_back_shockpot
(float shock1,uint16_t shock1_raw);

/**
* Contents of this message:
* MSB/B/RideHeight - Ride height to sensor
*/
uint8_t send_back_ride_height
(float rh);

/**
* Contents of this message:
* MSB/B/WheelTemp - As-measured wheel temperature
*/
uint8_t send_back_wheel_temp
(float wheel_temp);

/**
* Contents of this message:
* MSB/B/Orientation - MSB orientation as a result of sensor fusion
*/
uint8_t send_back_msb_orientation
(float x_fdeg,float y_fdeg,float z_fdeg);

/**
* Contents of this message:
* MSB/LoadCell1 - Load Cell 1 Data
* MSB/LoadCell2 - Load Cell 2 Data
*/
uint8_t send_load_cell_can_message
(uint16_t load_cell_1,uint16_t load_cell_2);

/**
* Contents of this message:
* MSB/WheelSpeedLeft - Left Wheel Speed Data
* MSB/WheelSpeedRight - Right Wheel Speed Data
*/
uint8_t send_wheel_speed
(uint16_t left_rpm,uint16_t right_rpm);

/**
* Contents of this message:
* MSB/SteeringAngle - Steering Angle Data
*/
uint8_t send_steering_angle
(int32_t steering_angle_1);

/**
* Contents of this message:
* MSB/Thermocouple1 - Thermocouple 1 Data
*/
uint8_t send_thermocouple
(int32_t thermocouple1);

/**
* Contents of this message:
* MSB/F/SSCPressure - Front SSC Pressure Reading
* MSB/F/SSCTemp - Front SSC Temperature Reading
*/
uint8_t send_front_msb_ssc
(float pressure,float temp);

/**
* Contents of this message:
* MSB/B/SSCPressure - Back SSC Pressure Reading
* MSB/B/SSCTemp - Back SSC Temperature Reading
*/
uint8_t send_back_msb_ssc
(float pressure,float temp);
#endif