#ifndef _CAN_MSGS_TX_H
#define _CAN_MSGS_TX_H

/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/
#include <stdbool.h>
#include <stdint.h>

/**
* Contents of this message:
* MSB/F/Temp - Temperature of board
* MSB/F/Humidity - Humidity of board
*/
uint8_t send_front_msb_env
(float temp,float humidity);

/**
* Contents of this message:
* MSB/F/Accel - IMU readings from the board
*/
uint8_t send_front_msb_accel
(float x_force,float y_force,float z_force);

/**
* Contents of this message:
* MSB/F/Gyro - Gyro readings from the board
*/
uint8_t send_front_msb_gyro
(float x_deg,float y_deg,float z_deg);

/**
* Contents of this message:
* MSB/F/Strain - Strain readings
*/
uint8_t send_front_msb_strain
(uint32_t strain1,uint32_t strain2);

/**
* Contents of this message:
* MSB/F/ShockLeft - Front-left shock deflection
* MSB/F/ShockRawLeft - Raw shock value
*/
uint8_t send_front_left_shockpot
(float shock_left,uint32_t shock_left_raw);

/**
* Contents of this message:
* MSB/F/RideHeight - Ride height to sensor
*/
uint8_t send_front_ride_height
(float rh);

/**
* Contents of this message:
* MSB/F/WheelTemp - As-measured wheel temperature
*/
uint8_t send_front_wheel_temp
(float wheel_temp);

/**
* Contents of this message:
* MSB/F/Orientation - MSB orientation as a result of sensor fusion
*/
uint8_t send_front_msb_orientation
(float x_fdeg,float y_fdeg,float z_fdeg);

/**
* Contents of this message:
* MSB/B/Temp - Temperature of board
* MSB/B/Humidity - Humidity of board
*/
uint8_t send_back_msb_env
(float temp,float humidity);

/**
* Contents of this message:
* MSB/B/Accel - IMU readings from the board
*/
uint8_t send_back_msb_accel
(float x_force,float y_force,float z_force);

/**
* Contents of this message:
* MSB/B/Gyro - Gyro readings from the board
*/
uint8_t send_back_msb_gyro
(float x_deg,float y_deg,float z_deg);

/**
* Contents of this message:
* MSB/B/Strain - Strain readings
*/
uint8_t send_back_msb_strain
(uint32_t strain1,uint32_t strain2);

/**
* Contents of this message:
* MSB/F/ShockRight - Front-right shock deflection
* MSB/F/ShockRawRight - Raw front-right shock value
*/
uint8_t send_front_right_shockpot
(float shock_right,uint32_t shock_right_raw);

/**
* Contents of this message:
* MSB/B/RideHeight - Ride height to sensor
*/
uint8_t send_back_ride_height
(float rh);

/**
* Contents of this message:
* MSB/B/WheelTemp - As-measured wheel temperature
*/
uint8_t send_back_wheel_temp
(float wheel_temp);

/**
* Contents of this message:
* MSB/B/Orientation - MSB orientation as a result of sensor fusion
*/
uint8_t send_back_msb_orientation
(float x_fdeg,float y_fdeg,float z_fdeg);

/**
* Contents of this message:
* MSB/F/WheelRPMLeft - Front-left wheel RPM
* MSB/F/WheelRPMRight - Front-right wheel RPM
*/
uint8_t send_front_wheel_rpm
(uint16_t left_rpm,uint16_t right_rpm);
#endif